// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sqrt.proto

package com.linadom.nikak;

public interface InputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.Input)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double number = 1;</code>
   * @return The number.
   */
  double getNumber();
}
