// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sqrt.proto

package com.linadom.nikak;

public interface OutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.Output)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double result = 1;</code>
   * @return The result.
   */
  double getResult();
}
