// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sqrt.proto

package com.linadom.nikak;

public final class Sqrt {
  private Sqrt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_Input_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calculator_Input_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_Output_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calculator_Output_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nsqrt.proto\022\ncalculator\"\027\n\005Input\022\016\n\006num" +
      "ber\030\001 \001(\001\"\030\n\006Output\022\016\n\006result\030\001 \001(\0012\374\001\n\021" +
      "CalculatorService\0223\n\010findSqrt\022\021.calculat" +
      "or.Input\032\022.calculator.Output\"\000\0226\n\007findMa" +
      "x\022\021.calculator.Input\032\022.calculator.Output" +
      "\"\000(\0010\001\022E\n\030getNumbersAllMultipliers\022\021.cal" +
      "culator.Input\032\022.calculator.Output\"\0000\001\0223\n" +
      "\006getSTD\022\021.calculator.Input\032\022.calculator." +
      "Output\"\000(\001B\025\n\021com.linadom.nikakP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_calculator_Input_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calculator_Input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calculator_Input_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_calculator_Output_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calculator_Output_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calculator_Output_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
